import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { color } from "../src/tokens/color.ts";
import { cssVar, pxToRem } from "../src/tokens/naming.ts";
import { palette } from "../src/tokens/palette.ts";
import { radius } from "../src/tokens/radius.ts";
import { spacing } from "../src/tokens/spacing.ts";
import { fontFamily, fontWeight, text } from "../src/tokens/typography.ts";

const OUTPUT_PATH = resolve(import.meta.dirname, "../src/styles/tokens.css");

function buildDeclarations(): string[] {
  const lines: string[] = [];

  for (const [key, value] of Object.entries(palette)) {
    lines.push(`  ${cssVar("palette", key)}: ${value.toLowerCase()};`);
  }

  for (const [key, primitiveKey] of Object.entries(color)) {
    lines.push(`  ${cssVar("color", key)}: var(${cssVar("palette", primitiveKey)});`);
  }

  for (const [key, value] of Object.entries(spacing)) {
    lines.push(`  ${cssVar("space", key)}: ${pxToRem(value)};`);
  }

  // Radius stays in px: `full` (100) is a "pill" shape hint, not a real
  // length meant to scale with the user's root font size like spacing/type.
  for (const [key, value] of Object.entries(radius)) {
    lines.push(`  ${cssVar("radius", key)}: ${value}px;`);
  }

  lines.push(`  ${cssVar("font", "family-base")}: ${fontFamily.base};`);
  lines.push(`  ${cssVar("font", "weight-bold")}: ${fontWeight.bold};`);
  for (const [key, style] of Object.entries(text)) {
    lines.push(`  ${cssVar("font", `${key}-size`)}: ${pxToRem(style.fontSize)};`);
    lines.push(`  ${cssVar("font", `${key}-line-height`)}: ${style.lineHeight};`);
  }

  return lines;
}

function buildCss(): string {
  const header = "/* Generated by scripts/generate-tokens.ts. Do not edit by hand. */";
  const declarations = buildDeclarations();
  return `${[header, ":root {", ...declarations, "}"].join("\n")}\n`;
}

writeFileSync(OUTPUT_PATH, buildCss(), { encoding: "utf8" });
